### ISSUE TITLE
Add workflow steps explicitly to episode 3

### ISSUE THREAD

**Issue by bpmweel** [carpentries-incubator/deep-learning-intro#117]
Currently the deep learning workflow steps are very explicit in episode 2, but they are completely gone in episode 3. We should add the there as well to help the learners in the steps to follow.

**Comment by dafnevk** [comment]
I want to +1 this issue because it's still relevant and came up last time we taught the workshop. It would be nice if episode 3 mimics the same structure as episode 2 in so far possible. Of course, beacuse we do hyperparameter optimization and prediction with the baseline, there is some going back and forth between the steps but that can also be made explicit.
