### ISSUE TITLE
How to continue lesson development?

### ISSUE THREAD

**Issue by svenvanderburg** [carpentries-incubator/deep-learning-intro#425]
I noticed that lately most activity in the repository is from me, and motivation to participate in the sprints is becoming less. Although I enjoy working on the lesson and I usually have time for it, it would of course be better (for many reasons) if the lesson is more driven by a community effort. This is an open question on how we should continue development in this repository.

Some ideas/questions:
* We currently have 1-day sprints every 2/3 months or so that are planned usually 2 months in advance. Should we change anything to this format?
* The lesson became more and more mature, teaching with it works really well, maybe there is not so much development needed anymore?
* If it just doesn't fit in your current list of tasks, but you would like to stay involved more on the side, it would be good to make that explicit.

I appreciate honest feedback! 🤗 

@dsmits @cpranav93 @CunliangGeng @colinsauze @psteinb what are your thoughts?

**Comment by cpranav93** [comment]
I am still quite interested in contributing to the lesson and from teaching the workshops and looking at the list of growing issues, I think that there is still quite a bit that can be developed to improve the material. I generally struggle with the format for the lesson development since one day is selected to work on the lesson (well in advance) but if something important comes up on that day then it is difficult to contribute then. A suggestion on my part would be to have maybe a 3-day sprint with stand-up once a day to check-in with whoever is available that day giving everyone more flexibility in planning their work here and otherwise.

**Comment by CunliangGeng** [comment]
I would opt out, though I'm still interested in AI stuff. 
There are two reasons: 
First, I have not been working on DL projects for quite a while. Considering the crazily rapid advance in DL, it's challenging for me to make sure what I could contribute is really the best practises. Ensuring that requires lots of effort, time and practical experience gained in projects. 
Second, I've largely lost interest in teaching (basics) since chatGPT came along. As I demonstrated in my internal presentation, self-help learning with chatGPT is effective and fun, and greatly lowers the barriers to learning various technologies.

**Comment by colinsauze** [comment]
Thank you for all your work on this lesson @svenvanderburg, its great to see the lesson heading towards the Carpentries Lab and the JOSE paper. I wish I had as much time to dedicate towards it as you have had. I'm still interested in developing this lesson but don't have much time I can spare and it isn't currently a core thing that I must work on. This might improve a little in the coming months, but I'm not certain yet.

I like @cpranav93's idea of a 3 day sprint, I would find it easier to find some time that I can contribute during a 3 day period than a 1 day period. Unfortunately a few sprints have clashed with days I'm unable to make. 

Is there a centralised place that the sprint dates are listed? For the last one I only got an email on November 1st (when I was away) for it happening on November 7th (when I was running a workshop), with more notice I might have been able to free up some time.

**Comment by svenvanderburg** [comment]
@colinsauze and @cpranav93 thank you for your suggestions. I like the 3-day sprint, I will schedule one for the new year soon. 

@colinsauze I'm super sorry it seems like I sent the announcement for the sprint on November 7th to your old email address.... I now marked the correct email address clearly in my mailbox so it won't happen again in the future. You can find the dates for upcoming lesson dev sprints here: https://github.com/carpentries-incubator/deep-learning-intro#lesson-development-sprints
