### ISSUE TITLE
[Lab Submission] Heading level skipped in prereq box

### ISSUE THREAD

**Issue by cpranav93** [carpentries-incubator/deep-learning-intro#430]
Point raised:
- there is a heading level skipped into the prereq box @tobyhodges is that an exception or an issue (or can you pull in the correct style person)

@tobyhodges, Is there any clarity on this?

**Comment by tobyhodges** [comment]
The heading level of the Prerequisites box is set by the Workbench lesson infrastructure, and cannot be controlled by us here. We could address it in the lesson itself by adding a second-level heading in the `index.md` file, above the prerequisites div. Perhaps `## Welcome` or similar? (We should avoid `## Introduction` because that is the title of the first episode.)

**Comment by svenvanderburg** [comment]
Ah, I see! I implemented your suggestion in #438
