### ISSUE TITLE
Tensorflow on Apple M1 Machine

### ISSUE THREAD

**Issue by PouriyaTUDelft** [carpentries-incubator/deep-learning-intro#441]
if you have Anaconda, installing tensorflow on an M1 machine seems impossible, at least to me :) . For more information and a possible solution see this Youtube video: https://www.youtube.com/watch?v=BEUU-icPg78&ab_channel=JeffHeaton

**Comment by tobyhodges** [comment]
Confirming that I also had this problem, and that -- although it felt rather extreme to delete and re-install my whole Anaconda setup -- the process described in the linked video largely solved the problem for me. The place where my process differed from that shown in the video is that I installed `tensorflow` with `pip` as described in the lesson setup instructions instead of with conda-forge/apple channels as I think the video shows. I am honestly not sure what difference this makes.

@svenvanderburg  would you like me to open a PR to update the setup page with this info?

**Comment by svenvanderburg** [comment]
@tobyhodges that would be great! I think for this course there are no notable differences between installing through pypi and conda-forge.
