### ISSUE TITLE
Episode 5 (optional): Transfer Learning  

### ISSUE THREAD

**Issue by dafnevk** [carpentries-incubator/deep-learning-intro#46]
## Learning objectives 
- How to re-use existing networks 
- Re-use an existing network on unbalanced data (something not classification?)

**Comment by svenvanderburg** [comment]
I like this lesson, because in some DL fields (like Natural Language Processing and Image classification) it is really weird to not use some form of transfer learning. 

It would be awesome if episode 4 (#45) would have an image dataset on which we can train to acceptable performance, but then if we use a pretrained model (we can show how to easily use one of the Keras ones) we get a performance boost.

**Comment by dafnevk** [comment]
I agree, we can explore if we can teach transfer learning in concise enough way, maybe extending on episode 4 (#45). 
I tried transfer learning on the CIFAR10 data set but didn't get it to work (yet), maybe because the images are so low-resolution that the features do not transfer properly. I'll try out some other datasets.

**Comment by svenvanderburg** [comment]
Obsolete with #456
