### ISSUE TITLE
Episode 7: Outlook 

### ISSUE THREAD

**Issue by dafnevk** [carpentries-incubator/deep-learning-intro#48]
## Learning objectives 
- Understand the relevance of the steps in the Deep Learning workflow 
- Explain when Deep Learning is a useful approach 
- List different applications for Deep Learning 
- Know where to find information on data generators 
- Know where to find more information about using GPUs for deep learning 
- Know where to find more information on using HPC for deep learning 

##Update after discussing with @dsmits :
We definitely need a concluding episode, even if it is a short one, it should include:
* A few real-world examples, see #362 
* Pointers to next steps (link to resources)

**Comment by svenvanderburg** [comment]
In my experience, a lot of the problems you encounter with deep learning in practice are related to using GPU. And it is really a hurdle in applying DL if you have no experience in accessing GPU machines, because for most problems you cannot apply DL if you don't have access or don't know how to run DL on GPU.

Would it be nice to instead of pointing to resources also teach a bit more on it? For example explain batch-size vs GPU memory, and that there are different types of GPU out there?

Preferably you would want some hands-on practice, I know in fast.ai they [have a nice free setup using google colab](https://course.fast.ai/start_colab#Using-a-GPU). You could do a simple exercise to at least have users experience that DL is so much faster on GPU.

**Comment by svenvanderburg** [comment]
In my experience (from industry) using HPC for DL is quite eccentric, so it would not make sense to teach about it in an intro course. But maybe you have other experience?

**Comment by svenvanderburg** [comment]
An IMO important question that is (explicitly) missing is: 'How do I select a model?'
