### ISSUE TITLE
Consistent use of Keras API

### ISSUE THREAD

**Issue by florian-huber** [carpentries-incubator/deep-learning-intro#50]
Keras is a really nice and accessible framework for doing deep learning. 
However, it can be used in multiple ways, most notably via using it the ``Sequential API``: https://keras.io/guides/sequential_model/
Or via the ``functional API``: https://keras.io/guides/functional_api/

In the past I have often seen that this quickly becomes very confusing. Keras is widely used, making it comparably easy to find hints and solutions for common problems in tutorials/forums. But the two APIs mentioned above can often not simply be combined so it can easily happen that one struggles to adapt a found solution if it is based on the other API choice. 

Although many beginner examples/tutorials start with the ``Sequential`` approach,  my own preference would be to work with the ``functional API`` since that is far more flexible (e.g. allows to also build more complex architectures and is not restricted to sequential architectures). For the planned content of this course, however, both APIs should work. 

So, whatever we decide on, it would be good to mostly use the same API throughout the lessons. Or what do you think?

**Comment by bpmweel** [comment]
@florian-huber I agree that the functional API would be preferable as it is more general.

We should probably spend a few sentences on this in the introduction to keras episode, because in the following example from their website the layer.Dense(...) function call returns a callable object which is then called with (x). This may be unfamiliar even for people with some python experience.
```
x = layers.Dense(64, activation="relu")(x)
```

However, if this is what we use consistently throughout the lesson the cognitive load should be manageable I think.

**Comment by psteinb** [comment]
For me, the decision boundary would always be, what people will use. From my little encounter with Keras in the wild, I think the functional API will be used more often.
