### ISSUE TITLE
Seaborn and/or matplotlib

### ISSUE THREAD

**Issue by dafnevk** [carpentries-incubator/deep-learning-intro#65]
I wonder what peoples opinions are on using seaborn and matplotlib for plotting in this lesson. Seaborn is a nice intuitive library, and I think we can use it for all loss and evalution plots. However, in episode 4 we need to plot images, which is not possible in seaborn (could be done with the additional package seaborn-image). Should we fall back on pure matplotlib plotting here, or would it introduce too much cognitive load to use two plotting libraries intertwined?

**Comment by colinsauze** [comment]
As matplotlib is taught in other carpentries lessons it would make sense to use it here. Fewer installation dependencies would be useful too. Is seaborn installed by default in anaconda or would people have to install it themselves?

**Comment by colinsauze** [comment]
to answer my own question, it looks like Seaborn is installed as part of Anaconda.

**Comment by bpmweel** [comment]
I originally chose seaborn because it allowed for plotting tabular data in a visually pleasant way with only 1 line of python code.
Using matplotlib for me feels very clunky usually and takes 6 or more lines, which I though might be bad for the cognitive load of people.
Having fewer dependencies is also nice, fewer things to go wrong for students.

In other words, I'm on the fence :)

But indeed matplotlib is taught in other carpentries so we can switch if others prefer.

**Comment by psteinb** [comment]
`seaborn` exposes less cognitive load. That is important.
