### ISSUE TITLE
glossary

### ISSUE THREAD

**Issue by psteinb** [carpentries-incubator/deep-learning-intro#76]
a glossary is a compilation of central terms of the lesson that can be integrated into this repo. A glossary can help both learners, contributors and instructors.

I suggest to start working on this, once episodes 1-3 (or even 1-4) have landed in the repo.

**Comment by psteinb** [comment]
Other carpentry lessons apparently contribute this by "hand", see [this glossary](https://swcarpentry.github.io/python-novice-inflammation/reference.html#glossary) rendered from this [input](https://github.com/swcarpentry/python-novice-inflammation/blob/gh-pages/reference.md)

**Comment by tobyhodges** [comment]
Now that [Glosario](https://glosario.carpentries.org/) exists, I believe a better way to handle lesson glossaries is to link from the terms to their definition in Glosario. You could still provide a list of terms on the Reference page, but as links to their entries in Glosario, rather than adding definitions in the lesson site itself.

Although this will require the learner to click through to the definition, it has the advantage of reducing redundancy of effort, and providing definitions in other languages for those learners that will be helped by this. And, of course, if you find any definitions missing from Glosario that you want to include in your lesson, you can define them there instead! 😁

**Comment by CunliangGeng** [comment]
Also related to #229 .

**Comment by dsmits** [comment]
I will open a PR where I linked to the existing definitions in glosario. I will open issues in the glosario repo for the missing definitions.
